---
title: "Converting SPSS syntax to R"
author: "Ashley L. Miller"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    theme: spacelab
    toc: true
    toc_float: true
    toc_depth: 5
    code_folding: show
---

```{r setup, include=FALSE}
# Set knitr options
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.width = 6,
                      fig.height = 4,
                      fig.align = "center")

# disable scientific notation
options(scipen = 999)

# load packages
library(devtools)
library(tidyverse)
#library(lme4)
library(rio)
library(here)
library(magrittr)
#library(lmerTest)
#library(sundry)
library(knitr)
library(kableExtra)
```

## Load data

```{r load_raw_data}
recall_data <- import(here::here("data",
                                 "AshRawDFRDemo.sav"),
                      setclass = "tibble") %>%
  janitor::clean_names() %>%
  dplyr::rename("error_type" = "err_pliel_ior_r")
```

Take a quick look at the data (for html view). Note, `subtrial` is simply output position.

```{r}
recall_data %>%
  kbl() %>%
  kable_styling(bootstrap_options = c("condensed", "responsive"),
                full_width = F) %>%
  column_spec(1, bold = T, border_right = T) %>%
  column_spec(2, width = "40em") %>%
  scroll_box(width = "100%", height = "225px")
```

